[package]
name = "protoplasm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_with = "3.12.0"
unicode-ident = "1.0.18"
